version: '3'
services:
  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: toolbox_postgres
    environment:
      POSTGRES_DB: toolbox_db
      POSTGRES_USER: toolbox_user
      POSTGRES_PASSWORD: secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - toolbox_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U toolbox_user -d toolbox_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: toolbox_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secure_password
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - toolbox_network

networks:
  toolbox_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_volume:
