version: '3'

services:
  ftp_server:
    image: fauria/vsftpd
    container_name: vsftpd
    ports:
      - "21:21"                   # Port FTP principal
      - "30000-30009:30000-30009" # Plage des ports passifs pour FTP
    environment:
      FTP_USER: admin              # Nom d'utilisateur
      FTP_PASS: jessica            # Mot de passe
      FTP_HOME: /home/admin        # Répertoire utilisateur
      PASV_ADDRESS: "127.0.0.1"    # Adresse IP locale pour les connexions passives
      PASV_MIN_PORT: 30000         # Premier port pour la plage passive
      PASV_MAX_PORT: 30009         # Dernier port pour la plage passive
    volumes:
      - "./ftpdata:/home/admin"    # Volume pour les fichiers
    restart: always
